version: '3'
services:
  project-processor-es:
    image: project-processor-es:latest
    build:
      context: ../
      dockerfile: docker/Dockerfile
    env_file:
      - api.env
    network_mode: "host"
